version: '3.8'
services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb_container
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: user
            MARIADB_PASSWORD: root
            MARIADB_DATABASE: admin
        ports:
            - "3333:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
